language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - dev
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 9
  - 8
script:
  - yarn test:prod && yarn build
after_success:
  - yarn report-coverage
  - yarn deploy-docs
  - yarn semantic-release
