language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - dev
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 9
  - 8
script:
  - yarn test:prod && if [[ $TRAVIS_BRANCH == 'master' ]]; then yarn build; fi
after_success:
  - yarn report-coverage
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then yarn travis-deploy-once "yarn deploy-docs"; fi
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then yarn travis-deploy-once "yarn semantic-release"; fi
