language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 9
  - 8
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - yarn test:prod && if [[ $TRAVIS_BRANCH == 'master' ]]; then yarn build; fi
after_success:
  - yarn report-coverage
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then greenkeeper-lockfile-upload ; fi
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then yarn travis-deploy-once "yarn deploy-docs"; fi
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then yarn travis-deploy-once "yarn semantic-release"; fi
