language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '9'
  - '8'
after_success:
  - coveralls < coverage/lcov.info
  - yarn run travis-deploy-once "yarn run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
